name: e2e-test

run-name: ${{ github.event_name }} at ${{ github.ref_name }} - ${{ github.actor }}

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install bcrypt
        run: yarn add bcrypt
      - name: Install Typeorm
        run: yarn global add typeorm
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn build
      - name: Run migrations in postgres db
        run: yarn typeorm migration:run -- -d ./db/postgres
      - name: Run e2e tests
        run: yarn test:e2e
        env:
          NODE_ENV: test
          PORT: 3000
          DATABASE_HOST: localhost
          DATABASE_USER: postgres
          DATABASE_PASSWORD: admin
          DATABASE_PORT: 5432
          DATABASE_NAME: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          JWT_SECRET: secret_test
